### ISSUE TITLE
Where can I find the sql?

### ISSUE THREAD

**Issue by net613** [Treeptik/cloudunit#145]
As the title, 3ks.

**Comment by GuillaumeMartial** [comment]
Hi Heng Wu,
Thank you for testing out app. 
I'm not really sure to understand, which sql are you talking about? The app loads all the data it needs at the first start.
Please check the development guide here : https://github.com/Treeptik/cloudunit/blob/dev/documentation/DEV-GUIDE-LINUX.md

Have I answered your question?

Best regards.

**Comment by net613** [comment]
hi @GuillaumeMartial, I find cloudunit is very interesting, and I want to test it. 
but unfortunately my OS is centos7, so I :
1. select cu-manager and import it into eclipse;
2. modify configuration.properties
3. execute the command "mvn clean install tomcat7:run -Dmaven.test.skip=true"
The exception is:
-----------------------------------

Aug 16, 2016 9:53:07 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationController': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private fr.treeptik.cloudunit.service.ApplicationService fr.treeptik.cloudunit.controller.ApplicationController.applicationService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationServiceImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private fr.treeptik.cloudunit.dao.ApplicationDAO fr.treeptik.cloudunit.service.impl.ApplicationServiceImpl.applicationDAO; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [fr.treeptik.cloudunit.dao.ApplicationDAO] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1210)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:434)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4937)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private fr.treeptik.cloudunit.service.ApplicationService fr.treeptik.cloudunit.controller.ApplicationController.applicationService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationServiceImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private fr.treeptik.cloudunit.dao.ApplicationDAO fr.treeptik.cloudunit.service.impl.ApplicationServiceImpl.applicationDAO; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [fr.treeptik.cloudunit.dao.ApplicationDAO] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}

--------------------------------------------------------

I find that there are no tables in database cloudunit, and It cannot find it, so I submit an Issue.
I really need your help.

Best regards.

**Comment by GuillaumeMartial** [comment]
In the command line you have run, the selected spring profile is missing. You must set the following JVM option when you run your maven command : -Dspring.profiles.active=[name of the profile] Two profiles are available : production and vagrant (for development) and one for integration testing.

However, if you want to install the packaged server version, you need to have a Ubuntu 14.04 with a kernel 3.13, 3.19 or 4.X. We have not already tested it on Centos. 
I think you tried to execute it directly on your machine. Have you got some errors when you run  the boot.sh script ?

I suggest you install the development version following the dev guide for Linux OS (here you will find all the information you need to do it, you can find vagrant and virtualbox for Centos : https://github.com/Treeptik/cloudunit/blob/dev/documentation/DEV-GUIDE-LINUX.md)
The vagrant box provides all what you need (docker, database, http proxy...) to run the project with vagrant profile (-Dspring.profiles.active=vagrant)

Let me know if you have any problem.

Best regards.

**Comment by net613** [comment]
Thank you, @GuillaumeMartial .
I have executed it directly on my machine with CentOS7.
